import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";

const originalArguments = [...process.argv];

afterEach(() => {
  process.argv = [...originalArguments];
  process.exitCode = undefined;
  vi.restoreAllMocks();
  vi.resetModules();
});

describe("OpenAPI CLI", () => {
  it("generates a file from the command-line entry point", async () => {
    const directory = await mkdtemp(resolve(tmpdir(), "uicogs-openapi-"));
    const output = resolve(directory, "generated", "api.ts");
    try {
      process.argv = [
        process.execPath,
        "uicogs-openapi",
        "generate",
        "tests/openapi-fixtures/neutral.json",
        "--output",
        output,
        "--strict",
      ];
      await import("./cli.js");
      await vi.waitFor(async () =>
        expect(await readFile(output, "utf8")).toContain("Generated by uicogs-openapi"),
      );
      expect(process.exitCode).toBeUndefined();
    } finally {
      await rm(directory, { recursive: true, force: true });
    }
  });

  it("reports usage and missing output without throwing an unhandled rejection", async () => {
    const write = vi.spyOn(process.stderr, "write").mockReturnValue(true);
    process.argv = [process.execPath, "uicogs-openapi"];
    await import("./cli.js");
    await vi.waitFor(() => expect(write).toHaveBeenCalledWith(expect.stringContaining("Usage:")));
    expect(process.exitCode).toBe(1);

    process.exitCode = undefined;
    write.mockClear();
    vi.resetModules();
    process.argv = [process.execPath, "uicogs-openapi", "generate", "fixture.json"];
    await import("./cli.js");
    await vi.waitFor(() =>
      expect(write).toHaveBeenCalledWith(expect.stringContaining("--output is required")),
    );
    expect(process.exitCode).toBe(1);
  });
});
