import { readFile } from "node:fs/promises";
import { parse as parseYaml } from "yaml";

export interface OpenApiDocument {
  readonly openapi: string;
  readonly components?: {
    readonly schemas?: Readonly<Record<string, OpenApiSchema>>;
  };
  readonly paths?: Readonly<Record<string, OpenApiPathItem>>;
}

export interface OpenApiSchema {
  readonly type?: string | readonly string[];
  readonly format?: string;
  readonly nullable?: boolean;
  readonly readOnly?: boolean;
  readonly writeOnly?: boolean;
  readonly enum?: readonly (string | number | boolean)[];
  readonly const?: string | number | boolean | null;
  readonly default?: unknown;
  readonly required?: readonly string[];
  readonly properties?: Readonly<Record<string, OpenApiSchema>>;
  readonly additionalProperties?: boolean | OpenApiSchema;
  readonly items?: OpenApiSchema;
  readonly $ref?: string;
  readonly allOf?: readonly OpenApiSchema[];
  readonly oneOf?: readonly OpenApiSchema[];
  readonly discriminator?: {
    readonly propertyName: string;
    readonly mapping?: Readonly<Record<string, string>>;
  };
  readonly minimum?: number;
  readonly maximum?: number;
  readonly minLength?: number;
  readonly maxLength?: number;
  readonly pattern?: string;
  readonly minItems?: number;
  readonly maxItems?: number;
}

export type OpenApiPathItem = Readonly<
  Record<string, OpenApiOperation | readonly OpenApiParameter[] | undefined>
> & {
  readonly parameters?: readonly OpenApiParameter[];
};

export interface OpenApiParameter {
  readonly name: string;
  readonly in: "query" | "path" | "header" | "cookie";
  readonly required?: boolean;
  readonly schema?: OpenApiSchema;
}

export interface OpenApiMediaType {
  readonly schema?: OpenApiSchema;
}

export interface OpenApiRequestBody {
  readonly required?: boolean;
  readonly content?: Readonly<Record<string, OpenApiMediaType>>;
}

export interface OpenApiResponse {
  readonly description?: string;
  readonly headers?: Readonly<Record<string, unknown>>;
  readonly content?: Readonly<Record<string, OpenApiMediaType>>;
}

export interface OpenApiOperation {
  readonly operationId?: string;
  readonly tags?: readonly string[];
  readonly parameters?: readonly OpenApiParameter[];
  readonly requestBody?: OpenApiRequestBody;
  readonly responses?: Readonly<Record<string, OpenApiResponse>>;
}

export interface GenerateOptions {
  readonly strict?: boolean;
  readonly runtimeImport?: string;
}

export interface GenerateResult {
  readonly code: string;
  readonly warnings: readonly string[];
}

interface GenerateContext {
  readonly schemas: Readonly<Record<string, OpenApiSchema>>;
  readonly warnings: string[];
  readonly declarationOrder: ReadonlyMap<string, number>;
  currentSchema?: string;
}

const methods = ["get", "post", "put", "patch", "delete"] as const;

export async function readOpenApi(input: string | OpenApiDocument): Promise<OpenApiDocument> {
  if (typeof input !== "string") return input;
  const text = await readFile(input, "utf8");
  const document = (
    input.endsWith(".json") ? JSON.parse(text) : parseYaml(text)
  ) as OpenApiDocument;
  if (!document.openapi?.startsWith("3."))
    throw new Error("UiCogs supports OpenAPI 3.0 and 3.1 documents");
  return document;
}

export function generateOpenApi(
  document: OpenApiDocument,
  options: GenerateOptions = {},
): GenerateResult {
  if (!document.openapi?.startsWith("3."))
    throw new Error("UiCogs supports OpenAPI 3.0 and 3.1 documents");
  const warnings: string[] = [];
  const schemas = document.components?.schemas ?? {};
  const ordered = orderSchemas(schemas, warnings);
  const context: GenerateContext = {
    schemas,
    warnings,
    declarationOrder: new Map(ordered.map((name, index) => [name, index])),
  };
  const lines = [
    "// Generated by uicogs-openapi. Do not edit.",
    `import { fields, schema } from ${JSON.stringify(options.runtimeImport ?? "@uicogs/core")};`,
    "",
    "export function createGeneratedDefinitions() {",
  ];

  for (const name of ordered) lines.push(...schemaDeclaration(name, schemas[name]!, context));
  context.currentSchema = undefined;

  const operationNames: string[] = [];
  const queryNames: string[] = [];
  for (const entry of operations(document)) {
    const generated = operationDeclaration(entry, context);
    lines.push(...generated.lines);
    operationNames.push(generated.name);
    if (generated.queryName) queryNames.push(generated.queryName);
  }

  lines.push(
    `  const schemas = Object.freeze({ ${ordered.map(safeName).join(", ")} });`,
    `  const operations = Object.freeze({ ${operationNames.join(", ")} });`,
    `  const queries = Object.freeze({ ${queryNames.join(", ")} });`,
    `  const resources = Object.freeze(${JSON.stringify(resourceHints(document), null, 2).replace(/^/gm, "  ").trimStart()});`,
    "  return Object.freeze({ schemas, operations, queries, resources });",
    "}",
    "",
  );
  if (options.strict && warnings.length) throw new Error(warnings.join("\n"));
  return { code: lines.join("\n"), warnings: Object.freeze(warnings) };
}

function schemaDeclaration(
  name: string,
  source: OpenApiSchema,
  context: GenerateContext,
): string[] {
  context.currentSchema = name;
  const variable = safeName(name);
  const inherited = (source.allOf ?? []).flatMap((item) => {
    if (!item.$ref) return [];
    const target = refName(item.$ref);
    return safeSchemaReference(target, context, name) ? [target] : [];
  });
  const local = flattenObject(source, context, name);
  if (!local.properties && inherited.length === 1)
    return [`  const ${variable} = ${safeName(inherited[0]!)};`];
  const base = objectSchemaExpression(local, context, name, "  ");
  if (!inherited.length) return [`  const ${variable} = ${base};`];
  const expression = inherited.reduce(
    (value, parent) => `${safeName(parent)}.merge(${value})`,
    base,
  );
  return [`  const ${variable} = ${expression};`];
}

function objectSchemaExpression(
  schema: OpenApiSchema,
  context: GenerateContext,
  path: string,
  indentation: string,
): string {
  const properties = schema.properties ?? {};
  const lines = ["schema({"];
  for (const name of Object.keys(properties).sort()) {
    lines.push(
      `${indentation}  ${safeProperty(name)}: ${fieldExpression(properties[name]!, schema.required?.includes(name) ?? false, context, `${path}.${name}`, `${indentation}  `)},`,
    );
  }
  lines.push(`${indentation}})`);
  return lines.join("\n");
}

function fieldExpression(
  schema: OpenApiSchema,
  required: boolean,
  context: GenerateContext,
  path: string,
  indentation: string,
): string {
  if (schema.$ref) return referencedField(schema, schema.$ref, required, context, path);
  if (schema.oneOf) {
    const refs = schema.oneOf.flatMap((item) => (item.$ref ? [refName(item.$ref)] : []));
    if (refs.length === schema.oneOf.length && schema.discriminator)
      return `fields.JSON(${configExpression(schema, required, {
        discriminator: schema.discriminator.propertyName,
        variants: refs,
      })})`;
    context.warnings.push(
      `${path}: oneOf without a reference discriminator is represented as typed JSON`,
    );
    return `fields.JSON(${configExpression(schema, required)})`;
  }
  const type = nonNullType(schema);
  if (schema.enum || schema.const !== undefined) {
    const values = schema.enum ?? [schema.const!];
    return `fields.Enum(${JSON.stringify(values)} as const, ${configExpression(schema, required)})`;
  }
  if (type === "array") return arrayField(schema, required, context, path, indentation);
  if (type === "object" || schema.properties) {
    if (!schema.properties && schema.additionalProperties)
      return `fields.Record(${configExpression(schema, required)})`;
    const nested = objectSchemaExpression(schema, context, path, `${indentation}  `);
    return `fields.Object(${nested}, ${configExpression(schema, required)})`;
  }
  const factory = stringFactory(schema) ?? scalarFactory(type);
  if (factory) return `fields.${factory}(${configExpression(schema, required)})`;
  context.warnings.push(
    `${path}: unsupported schema type ${String(type)}; represented as typed JSON`,
  );
  return `fields.JSON(${configExpression(schema, required)})`;
}

function arrayField(
  schema: OpenApiSchema,
  required: boolean,
  context: GenerateContext,
  path: string,
  indentation: string,
): string {
  const item = schema.items;
  if (!item) {
    context.warnings.push(`${path}: array has no items schema; represented as typed JSON`);
    return `fields.JSON(${configExpression(schema, required)})`;
  }
  const config = configExpression(schema, required);
  if (item.$ref) return `fields.ObjectList(${safeName(refName(item.$ref))}, ${config})`;
  if (item.properties || nonNullType(item) === "object") {
    const nested = objectSchemaExpression(item, context, `${path}[]`, `${indentation}  `);
    return `fields.ObjectList(${nested}, ${config})`;
  }
  if (item.enum) return `fields.EnumList(${JSON.stringify(item.enum)} as const, ${config})`;
  if (nonNullType(item) === "string") return `fields.StrList(${config})`;
  if (nonNullType(item) === "integer") return `fields.IntList(${config})`;
  context.warnings.push(`${path}: array item type is represented as typed JSON`);
  return `fields.JSON(${config})`;
}

function configExpression(
  schema: OpenApiSchema,
  required: boolean,
  metadata?: Readonly<Record<string, unknown>>,
): string {
  const config: string[] = [];
  if (required) config.push("required: true");
  if (schema.readOnly) config.push("readonly: true");
  if (schema.writeOnly) config.push("writeonly: true");
  if (schema.nullable || (Array.isArray(schema.type) && schema.type.includes("null")))
    config.push("nullable: true");
  if (schema.default !== undefined) config.push(`default: ${JSON.stringify(schema.default)}`);
  if (schema.minLength !== undefined) config.push(`minLength: ${schema.minLength}`);
  if (schema.maxLength !== undefined) config.push(`maxLength: ${schema.maxLength}`);
  if (schema.minimum !== undefined) config.push(`min: ${schema.minimum}`);
  if (schema.maximum !== undefined) config.push(`max: ${schema.maximum}`);
  if (schema.pattern) config.push(`pattern: new RegExp(${JSON.stringify(schema.pattern)})`);
  if (metadata) config.push(`metadata: { openapi: ${JSON.stringify(metadata)} }`);
  return `{ ${config.join(", ")} }`;
}

interface OperationEntry {
  readonly path: string;
  readonly method: (typeof methods)[number];
  readonly operation: OpenApiOperation;
  readonly inheritedParameters: readonly OpenApiParameter[];
}

function operations(document: OpenApiDocument): readonly OperationEntry[] {
  const output: OperationEntry[] = [];
  for (const path of Object.keys(document.paths ?? {}).sort()) {
    const item = document.paths?.[path];
    if (!item) continue;
    const inheritedParameters = Array.isArray(item.parameters) ? item.parameters : [];
    for (const method of methods) {
      const operation = item[method];
      if (!isOperation(operation)) continue;
      output.push({ path, method, operation, inheritedParameters });
    }
  }
  return output;
}

function operationDeclaration(
  entry: OperationEntry,
  context: GenerateContext,
): { readonly name: string; readonly queryName?: string; readonly lines: string[] } {
  const name = safeName(
    entry.operation.operationId ?? generatedOperationName(entry.method, entry.path),
  );
  const parameters = [...entry.inheritedParameters, ...(entry.operation.parameters ?? [])];
  const query = parameters.filter((parameter) => parameter.in === "query" && parameter.schema);
  const queryName = query.length ? `${name}Query` : undefined;
  const lines: string[] = [];
  if (queryName) {
    lines.push(`  const ${queryName} = schema({`);
    for (const parameter of query.sort((left, right) => left.name.localeCompare(right.name)))
      lines.push(
        `    ${safeProperty(parameter.name)}: ${fieldExpression(parameter.schema!, parameter.required ?? false, context, `${name}.query.${parameter.name}`, "    ")},`,
      );
    lines.push("  });");
  }
  const requestSchema = mediaSchema(entry.operation.requestBody?.content);
  const responseSchema = successfulResponseSchema(entry.operation.responses);
  const requestName = requestSchema
    ? operationSchemaDeclaration(`${name}Input`, requestSchema, context, lines)
    : undefined;
  const response = responseSchema
    ? operationResponseDeclaration(`${name}Output`, responseSchema, context, lines)
    : undefined;
  lines.push(`  const ${name} = Object.freeze({`);
  lines.push(`    method: ${JSON.stringify(entry.method.toUpperCase())},`);
  lines.push(`    path: ${JSON.stringify(entry.path)},`);
  if (queryName) lines.push(`    query: ${queryName},`);
  if (requestName) lines.push(`    input: ${requestName},`);
  if (response?.name) lines.push(`    output: ${response.name},`);
  if (response?.many) lines.push("    many: true,");
  if (entry.operation.requestBody?.content)
    lines.push(
      `    encoding: ${JSON.stringify(requestEncoding(entry.operation.requestBody.content))},`,
    );
  lines.push(
    `    responses: Object.freeze(${JSON.stringify(responseHints(entry.operation.responses))}),`,
  );
  lines.push("  });");
  return { name, ...(queryName ? { queryName } : {}), lines };
}

function operationSchemaDeclaration(
  name: string,
  schema: OpenApiSchema,
  context: GenerateContext,
  lines: string[],
): string | undefined {
  if (schema.$ref) {
    const target = refName(schema.$ref);
    if (context.schemas[target]) return safeName(target);
    addWarning(context, `${name}: reference ${schema.$ref} was not found`);
    return undefined;
  }
  if (nonNullType(schema) === "object" || schema.properties) {
    const variable = safeName(name);
    lines.push(`  const ${variable} = ${objectSchemaExpression(schema, context, name, "  ")};`);
    return variable;
  }
  addWarning(context, `${name}: operation payload is not an object schema`);
  return undefined;
}

function operationResponseDeclaration(
  name: string,
  schema: OpenApiSchema,
  context: GenerateContext,
  lines: string[],
): { readonly name?: string; readonly many: boolean } {
  if (nonNullType(schema) === "array") {
    if (!schema.items) {
      addWarning(context, `${name}: response array has no items schema`);
      return { many: true };
    }
    const output = operationSchemaDeclaration(name, schema.items, context, lines);
    return { ...(output ? { name: output } : {}), many: true };
  }
  const output = operationSchemaDeclaration(name, schema, context, lines);
  return { ...(output ? { name: output } : {}), many: false };
}

function resourceHints(document: OpenApiDocument): readonly Readonly<Record<string, unknown>>[] {
  const groups = new Map<string, { paths: Set<string>; operations: string[] }>();
  for (const entry of operations(document)) {
    const tag = entry.operation.tags?.[0] ?? firstPathSegment(entry.path) ?? "default";
    const group = groups.get(tag) ?? { paths: new Set(), operations: [] };
    group.paths.add(entry.path);
    group.operations.push(
      entry.operation.operationId ?? generatedOperationName(entry.method, entry.path),
    );
    groups.set(tag, group);
  }
  return [...groups.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, group]) =>
      Object.freeze({
        name,
        url: commonResourcePath([...group.paths]),
        operations: Object.freeze([...group.operations].sort()),
      }),
    );
}

function orderSchemas(
  schemas: Readonly<Record<string, OpenApiSchema>>,
  warnings: string[],
): readonly string[] {
  const output: string[] = [];
  const visiting = new Set<string>();
  const visited = new Set<string>();
  const visit = (name: string): void => {
    if (visited.has(name)) return;
    if (visiting.has(name)) {
      warnings.push(`${name}: cyclic schema references require a manual lazy relation override`);
      return;
    }
    visiting.add(name);
    for (const dependency of referencedSchemas(schemas[name]))
      if (schemas[dependency]) visit(dependency);
    visiting.delete(name);
    visited.add(name);
    output.push(name);
  };
  for (const name of Object.keys(schemas).sort()) visit(name);
  return output;
}

function referencedField(
  schema: OpenApiSchema,
  reference: string,
  required: boolean,
  context: GenerateContext,
  path: string,
): string {
  const target = refName(reference);
  if (!safeSchemaReference(target, context, path))
    return `fields.JSON(${configExpression(schema, required, { reference })})`;
  return `fields.Object(${safeName(target)}, ${configExpression(schema, required)})`;
}

function safeSchemaReference(target: string, context: GenerateContext, path: string): boolean {
  if (!context.schemas[target]) {
    addWarning(context, `${path}: reference ${target} was not found`);
    return false;
  }
  if (!context.currentSchema) return true;
  const current = context.declarationOrder.get(context.currentSchema);
  const dependency = context.declarationOrder.get(target);
  if (current !== undefined && dependency !== undefined && dependency >= current) {
    addWarning(context, `${path}: cyclic reference to ${target} is represented as typed JSON`);
    return false;
  }
  return true;
}

function addWarning(context: GenerateContext, warning: string): void {
  if (!context.warnings.includes(warning)) context.warnings.push(warning);
}

function referencedSchemas(schema: OpenApiSchema | undefined): readonly string[] {
  if (!schema) return [];
  return [
    ...new Set([
      ...(schema.$ref ? [refName(schema.$ref)] : []),
      ...(schema.items ? referencedSchemas(schema.items) : []),
      ...Object.values(schema.properties ?? {}).flatMap(referencedSchemas),
      ...(schema.allOf ?? []).flatMap(referencedSchemas),
      ...(schema.oneOf ?? []).flatMap(referencedSchemas),
    ]),
  ];
}

function flattenObject(
  schema: OpenApiSchema,
  context: GenerateContext,
  path: string,
): OpenApiSchema {
  const inline = (schema.allOf ?? []).filter((item) => !item.$ref);
  if (inline.some((item) => item.oneOf))
    context.warnings.push(`${path}: nested allOf/oneOf composition is represented conservatively`);
  return {
    ...schema,
    properties: Object.freeze(
      Object.assign({}, ...inline.map((item) => item.properties ?? {}), schema.properties ?? {}),
    ),
    required: Object.freeze([
      ...new Set([...inline.flatMap((item) => item.required ?? []), ...(schema.required ?? [])]),
    ]),
  };
}

function mediaSchema(
  content: Readonly<Record<string, OpenApiMediaType>> | undefined,
): OpenApiSchema | undefined {
  if (!content) return undefined;
  return (
    content["application/json"]?.schema ??
    content["multipart/form-data"]?.schema ??
    Object.values(content)[0]?.schema
  );
}

function successfulResponseSchema(
  responses: Readonly<Record<string, OpenApiResponse>> | undefined,
): OpenApiSchema | undefined {
  if (!responses) return undefined;
  const key =
    Object.keys(responses)
      .sort()
      .find((status) => /^2\d\d$/.test(status)) ?? "default";
  return mediaSchema(responses[key]?.content);
}

function requestEncoding(
  content: Readonly<Record<string, OpenApiMediaType>>,
): "json" | "multipart" | "auto" {
  if (content["multipart/form-data"]) return "multipart";
  if (content["application/json"]) return "json";
  return "auto";
}

function responseHints(
  responses: Readonly<Record<string, OpenApiResponse>> | undefined,
): readonly string[] {
  return Object.keys(responses ?? {}).sort();
}

function stringFactory(schema: OpenApiSchema): string | undefined {
  if (nonNullType(schema) !== "string") return undefined;
  if (schema.format === "email") return "Email";
  if (schema.format === "password") return "Password";
  if (schema.format === "date") return "Date";
  if (schema.format === "date-time") return "DateTime";
  if (schema.format === "time") return "Time";
  if (schema.format === "binary") return "File";
  return "Str";
}

function scalarFactory(type: string | undefined): string | undefined {
  if (type === "integer") return "Int";
  if (type === "number") return "Float";
  if (type === "boolean") return "Bool";
  if (type === "string" || type === undefined) return "Str";
  return undefined;
}

function nonNullType(schema: OpenApiSchema): string | undefined {
  return typeof schema.type === "string"
    ? schema.type
    : schema.type?.find((type) => type !== "null");
}

function isOperation(value: unknown): value is OpenApiOperation {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function refName(reference: string): string {
  const value = reference.split("/").pop();
  if (!value) throw new Error(`Invalid OpenAPI reference ${reference}`);
  return decodeURIComponent(value);
}

function safeName(value: string): string {
  const normalized = value.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[A-Za-z_$]/.test(normalized) ? normalized : `_${normalized}`;
}

function safeProperty(value: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(value) ? value : JSON.stringify(value);
}

function generatedOperationName(method: string, path: string): string {
  const segments = path
    .split("/")
    .filter(Boolean)
    .map((segment) => segment.replace(/[{}]/g, ""));
  return safeName(`${method}_${segments.join("_") || "root"}`);
}

function firstPathSegment(path: string): string | undefined {
  return path.split("/").find((segment) => segment && !segment.startsWith("{"));
}

function commonResourcePath(paths: readonly string[]): string {
  if (!paths.length) return "/";
  const segments = paths.map((path) => path.split("/").filter(Boolean));
  const common: string[] = [];
  for (let index = 0; ; index += 1) {
    const value = segments[0]?.[index];
    if (!value || value.startsWith("{") || segments.some((parts) => parts[index] !== value)) break;
    common.push(value);
  }
  return `/${common.join("/")}${common.length ? "/" : ""}`;
}
