// Generated by uicogs-openapi. Do not edit.
import { fields, schema } from "@uicogs/core";

export function createGeneratedDefinitions() {
  const User = schema({
    email: fields.Email({ required: true }),
    id: fields.Int({ required: true, readonly: true }),
  });
  const Project = schema({
    id: fields.Int({ required: true, readonly: true }),
    name: fields.Str({ required: true, minLength: 2 }),
    owner: fields.Object(User, {  }),
  });
  const listProjectsQuery = schema({
    search: fields.Str({  }),
  });
  const listProjects = Object.freeze({
    method: "GET",
    path: "/projects/",
    query: listProjectsQuery,
    output: Project,
    many: true,
    responses: Object.freeze(["200"]),
  });
  const schemas = Object.freeze({ User, Project });
  const operations = Object.freeze({ listProjects });
  const queries = Object.freeze({ listProjectsQuery });
  const resources = Object.freeze([
    {
      "name": "projects",
      "url": "/projects/",
      "operations": [
        "listProjects"
      ]
    }
  ]);
  return Object.freeze({ schemas, operations, queries, resources });
}
